---

- name: check for the marker
  stat:
    path: "{{ oracle_tmp }}/database/copied"
  register: unzipped
  ignore_errors: yes

- name: unzip installer
  unarchive:
    src: "{{ item.image }}"
    dest: "{{ oracle_tmp }}"
    remote_src: no
    keep_newer: yes
#  when: item.version == "{{ oracle_version }}" and unzipped.stat.exists == no
  with_items:
   -  "{{ oracle_images }}"
- name: chown of installer
  command: chown -R oracle:oinstall /tmp/oracle/database/runInstaller

  
- name: place a marker for the completion
  file:
    path: "{{ oracle_tmp }}/database/copied"
    state: touch
